### ISSUE TITLE
dev:demo  运行报错

### ISSUE THREAD

**Issue by hkc452** [CareyToboo/ovine#30]
/mnt/d/oode/ovine/packages/core/lib/styled/theme.js
Module not found: Can't resolve '@generated/styles/themes' in '/mnt/d/oode/ovine/packages/core/lib/styled'
/mnt/d/oode/ovine/website/example/node_modules/@ovine/cli/lib/webpack/base.js:434
    var themes = cssAssets.map(function (i) { return "" + publicPath + i; });
                           ^

TypeError: cssAssets.map is not a function
    at getThemeScript (/mnt/d/oode/ovine/website/example/node_modules/@ovine/cli/lib/webpack/base.js:434:28)
    at getThemeScript (/mnt/d/oode/ovine/website/example/node_modules/@ovine/cli/lib/webpack/base.js:363:62)
    at /mnt/d/oode/ovine/website/example/node_modules/@ovine/cli/lib/webpack/plugins/html_hooks_plugin.js:40:11
    at Immediate.<anonymous> (/mnt/d/oode/ovine/node_modules/memory-fs/lib/MemoryFileSystem.js:309:4)
    at processImmediate (internal/timers.js:456:21)
error Command failed with exit code 1.

**Comment by CareyToboo** [comment]
先看下这个吧  [开发者指南](https://ovine.igroupes.com/org/blog/contribute)

`yarn dev:demo` 这个命令我也没有用过。因为不常用，有问题也没有注意。而且现在项目变大以后，有些命令确实有点繁琐，命令后期这块我要整理一下，入手起来，方便一点。
